# Generated by Django 4.1 on 2024-06-13 14:44

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employes_id_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id_project',
        ),
        migrations.AddField(
            model_name='project',
            name='teamleader_employee_id',
            field=models.ForeignKey(default=users.models.create_placeholder_employee, on_delete=django.db.models.deletion.CASCADE, to='users.employes'),
        ),
    ]
