# Generated by Django 5.0.3 on 2024-04-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='experiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_experiment', models.CharField(max_length=45, verbose_name='Name of the experiment')),
                ('start_date', models.DateField(verbose_name='Start')),
                ('end_date', models.DateField(verbose_name='End')),
                ('status', models.CharField(max_length=45, verbose_name='Status of the experiment')),
                ('description_of_results', models.CharField(max_length=45, verbose_name='Description results')),
            ],
        ),
        migrations.CreateModel(
            name='laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Name of the laboratory')),
                ('address', models.CharField(max_length=45, verbose_name='Address of the laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Name of the patient')),
                ('last_name', models.CharField(max_length=45, verbose_name='Last Name of the patient')),
                ('sex', models.CharField(max_length=1, verbose_name='Sex of the patient')),
                ('DOB', models.DateField(verbose_name='Date of birth')),
                ('pesel', models.IntegerField(verbose_name='Pesel of the patient')),
                ('phone_number', models.IntegerField(verbose_name='Phone number of the patient')),
                ('email', models.EmailField(max_length=254, verbose_name='Email of the patient')),
                ('group', models.CharField(max_length=45, verbose_name='Group of the patient')),
                ('address', models.CharField(max_length=45, verbose_name='Address of the patient')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_project', models.CharField(max_length=45, verbose_name='Name of the project')),
                ('description', models.CharField(max_length=45, verbose_name='Description of the project')),
                ('start_date', models.DateField(verbose_name='Start')),
                ('end_date', models.DateField(verbose_name='End')),
            ],
        ),
        migrations.CreateModel(
            name='keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=45, verbose_name='Key word')),
                ('id_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.experiments')),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
            ],
        ),
        migrations.AddField(
            model_name='experiments',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project'),
        ),
        migrations.CreateModel(
            name='employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=45, verbose_name='Last Name')),
                ('login', models.CharField(max_length=45, verbose_name='Login')),
                ('password', models.CharField(max_length=45, verbose_name='Password')),
                ('email', models.EmailField(max_length=45, verbose_name='Email')),
                ('pesel', models.IntegerField(verbose_name='Pesel')),
                ('phone_number', models.IntegerField(verbose_name='Phone Number')),
                ('id_experiments', models.ManyToManyField(to='users.experiments')),
                ('id_lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.laboratory')),
                ('id_project', models.ManyToManyField(to='users.project')),
            ],
        ),
        migrations.CreateModel(
            name='protocols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_name', models.CharField(max_length=45, verbose_name='Name of the protocol')),
                ('id_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.experiments')),
            ],
        ),
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=45, verbose_name='Filename')),
                ('id_experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.experiments')),
            ],
        ),
    ]
